index:
    path: /
    controller: App\Controller\Dashboard\DashboardController
    methods:    GET

job_status:
    path: /status/{status}
    controller: App\Controller\Dashboard\DashboardController::filterByStatus
    methods: GET

job_form:
    path: /jobs/form
    controller: App\Controller\Job\JobFormController
    methods:    GET|POST

job_edit:
    path: /jobs/edit/{id}
    controller: App\Controller\Job\JobFormController
    methods:    GET|POST

job_delete:
    path: /jobs/delete/{id}
    controller: App\Controller\Job\JobDeleteController
    methods:    GET

company:
    path: /companies
    controller: App\Controller\Company\CompanyController
    methods:    GET

company_form:
    path: /companies/form
    controller: App\Controller\Company\CompanyFormController
    methods:    GET|POST

company_edit:
    path: /companies/edit/{id}
    controller: App\Controller\Company\CompanyFormController
    methods:    GET|POST

company_delete:
    path: /companies/delete/{id}
    controller: App\Controller\Company\CompanyDeleteController
    methods:    GET

platform:
    path: /platforms
    controller: App\Controller\Platform\PlatformController
    methods:    GET

platform_form:
    path: /platforms/form
    controller: App\Controller\Platform\PlatformFormController
    methods:    GET|POST

platform_edit:
    path: /platforms/edit/{id}
    controller: App\Controller\Platform\PlatformFormController
    methods:    GET|POST

platform_delete:
    path: /platforms/delete/{id}
    controller: App\Controller\Platform\PlatformDeleteController
    methods:    GET|POST

resume:
    path: /resumes
    controller: App\Controller\Resume\ResumeController
    methods: GET

resume_preview:
    path: /resumes/preview/{id}
    controller: App\Controller\Resume\ResumePreviewController
    methods: GET

resume_form:
    path: /resumes/form
    controller: App\Controller\Resume\ResumeFormController
    methods: GET|POST

resume_edit:
    path: /resumes/edit/{id}
    controller: App\Controller\Resume\ResumeFormController
    methods: GET|POST

resume_delete:
    path: /resumes/delete/{id}
    controller: App\Controller\Resume\ResumeDeleteController
    methods: GET|POST
