index:
    path: /
    controller: App\Controller\Dashboard\DashboardController
    methods:    GET

job_form:
    path: /jobs/form
    controller: App\Controller\Job\JobFormController
    methods:    GET|POST

job_edit:
    path: /jobs/edit/{id}
    controller: App\Controller\Job\JobFormController
    methods:    GET|POST

job_delete:
    path: /jobs/delete/{id}
    controller: App\Controller\Job\JobDeleteController
    methods:    GET

company:
    path: /companies
    controller: App\Controller\Company\CompanyController
    methods:    GET

company_form:
    path: /companies/form
    controller: App\Controller\Company\CompanyFormController
    methods:    GET|POST

company_edit:
    path: /companies/edit/{id}
    controller: App\Controller\Company\CompanyFormController
    methods:    GET|POST

company_delete:
    path: /companies/delete/{id}
    controller: App\Controller\Company\CompanyDeleteController
    methods:    GET


